<!DOCTYPE html>
<html>
<head>
    <title><?php echo $response->getStatusCode() ?> <?php echo $response->getStatusReasonPhrase() ?></title>
    <style>
        body {
            width: 45em;
            margin: 0 auto;
            font-family: Helvetica, Arial, sans-serif;
            text-align: center;
        }
        h1 {
            font-size: 350%;
            font-weight: bold;
        }
        .exception {
            background-color: black;
            color: white;
            font-family: "Courier New", Courier, monospace, serif;
            font-size: 65%;
            text-align: left;
            padding: 15px;
            -moz-border-radius: 15px;
            border-radius: 15px;
            overflow-x: scroll;
        }
        footer {
            margin-top: 30px;
        }
    </style>
</head>
<body>

<header>
    <h1><?php echo $response->getStatusCode() ?> <?php echo $response->getStatusReasonPhrase() ?></h1>
</header>

<p class="exception"><?php echo $errorMessage ?></p>

<p>Please report bugs to<br/>
    <a href="https://github.com/techdivision/TechDivision_WebServer/issues/new">https://github.com/techdivision/TechDivision_WebServer/issues/new</a>
</p>

<p>For online documentation and support please refer to<br/>
    <a href="http://github.com/techdivision/TechDivision_WebServer">http://github.com/techdivision/TechDivision_WebServer</a>.
</p>

<footer>
    <?php echo $this->getServerContext()->getServerVar('SERVER_SIGNATURE') ?>
</footer>
</body>
</html>