<?php
/**
 * \TechDivision\WebServer\Modules\PhpProcess
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * PHP version 5
 *
 * @category   Webserver
 * @package    TechDivision_WebServer
 * @subpackage Modules
 * @author     Johann Zelger <jz@techdivision.com>
 * @copyright  2014 TechDivision GmbH <info@techdivision.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       https://github.com/techdivision/TechDivision_WebServer
 */

namespace TechDivision\WebServer\Modules;

/**
 * Class PhpProcess
 *
 * @category   Webserver
 * @package    TechDivision_WebServer
 * @subpackage Modules
 * @author     Johann Zelger <jz@techdivision.com>
 * @copyright  2014 TechDivision GmbH <info@techdivision.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       https://github.com/techdivision/TechDivision_WebServer
 */
class PhpProcess
{
    /**
     * Hold's the headers as array
     *
     * @var array
     */
    public $headers;

    /**
     * Hold's the output buffer generated by process run
     *
     * @var string
     */
    public $outputBuffer;

    /**
     * Hold's the uploaded filename's
     *
     * @var array
     */
    protected $uploadedFiles;

    /**
     * Constructs the process
     *
     * @param string                                     $scriptFilename The script filename to execute
     * @param \TechDivision\WebServer\Modules\PhpGlobals $globals        The globals instance
     * @param array                                      $uploadedFiles  The uploaded files as array
     */
    public function __construct($scriptFilename, PhpGlobals $globals, array $uploadedFiles = array())
    {
        $this->scriptFilename = $scriptFilename;
        $this->globals = $globals;
        $this->uploadedFiles = $uploadedFiles;
    }

    /**
     * Run's the process
     *
     * @param int $flags Flags how to start the process
     *
     * @return void
     */
    public function start($flags)
    {
        // init globals to local var
        $globals = $this->globals;
        // start output buffering
        ob_start();
        // set globals
        $_SERVER = $globals->server;
        $_REQUEST = $globals->request;
        $_POST = $globals->post;
        $_GET = $globals->get;
        $_COOKIE = $globals->cookie;
        $_FILES = $globals->files;

        // get current working dir for reset after processing
        $oldCwd = getcwd();
        // change dir to be in real php process context
        chdir(dirname($this->scriptFilename));
        // reset headers sent
        appserver_set_headers_sent(false);
        // require script filename
        require $this->scriptFilename;
        // change dir to old cwd
        chdir($oldCwd);
    }

    /**
     * Waits for the process to be finished and provides properties to be set when finished.
     *
     * @return bool
     */
    public function join()
    {
        // set headers set by script inclusion
        $this->headers = appserver_get_headers(true);
        // set output buffer set by script inclusion
        $this->outputBuffer = ob_get_clean();
    }

    /**
     * Return's the output buffer
     *
     * @return string
     */
    public function getOutputBuffer()
    {
        return $this->outputBuffer;
    }

    /**
     * Return's the headers array
     *
     * @return array
     */
    public function getHeaders()
    {
        return $this->headers;
    }
}
