<?php /** @var \AppserverIo\Server\Interfaces\ConnectionHandlerInterface $this */ ?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><?php echo $response->getStatusCode() ?> <?php echo $response->getStatusReasonPhrase() ?></title>
<style>
    body { width: 80%; margin: 0 auto; font-family: Helvetica, Arial, sans-serif; text-align: center; }
    footer { margin-top: 30px; }
    .exception { background-color: black; color: white; font-family: "Courier New", Courier, monospace, serif; font-size: 65%; text-align: left; padding: 15px; -moz-border-radius: 15px; border-radius: 15px; overflow-x: scroll; }
</style>
</head>
<body>

<header>
    <h1><?php echo $response->getStatusCode() ?> <?php echo $response->getStatusReasonPhrase() ?></h1>
</header>

<p class="exception"><?php echo $errorMessage ?></p>

<p>Please report bugs to<br/>
    <a href="https://github.com/appserver-io/webserver/issues/new">https://github.com/appserver-io/webserver/issues/new</a>
</p>

<p>For online documentation and support please refer to<br/>
    <a href="http://github.com/appserver-io/webserver">http://github.com/appserver-io/webserver</a>.
</p>

<footer>
    <?php echo $this->getRequestContext()->getServerVar('SERVER_SIGNATURE') ?>
</footer>
</body>
</html>